### ISSUE TITLE
Not including styles.

### ISSUE THREAD

**Issue by hubbubca** [emiloberg/markdown-styleguide-generator#5]
I'm sure this is me doing something wrong, but the styles aren't rendering.  The glyphs not showing up doesn't surprise me, the rest does though.

Here's a screenshot

![screen shot 2015-06-07 at 15 04 21](https://cloud.githubusercontent.com/assets/194711/8025528/13762842-0d27-11e5-8ae7-b38c201d8297.png)

Any help would be splendid :)

**Comment by emiloberg** [comment]
How does the css-file look like, do you actually have the `icon-search` and `glyph-1x` classes? And do they output anything?

**Comment by hubbubca** [comment]
That's not what is bothering me, it's the non styling of the left bar etc 😃

**Comment by emiloberg** [comment]
This style guide tool includes as little styling as possible (as all styling should be inherited from the _real_ stylesheet of your website). If you're referring to that the font family of the side bar is different from the one in the [readme screenshot](https://raw.githubusercontent.com/emiloberg/markdown-styleguide-generator/master/docs/screenshot-sample.png) this is simply because the readme screenshot has inherited styles. 

If you want to add styles (e.g. to the side bar) you can [add the css to the template](https://github.com/emiloberg/markdown-styleguide-generator#custom-look-and-feel).

Does this help you?

**Comment by hubbubca** [comment]
This is perfect,  thank you!   😀
